// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHswyxR7Gpgu2GsUpnbNQVvV0XcQ-amzk',
    appId: '1:331639738061:web:4641cab35210938f78e384',
    messagingSenderId: '331639738061',
    projectId: 'admasmarket-ef29a',
    authDomain: 'admasmarket-ef29a.firebaseapp.com',
    storageBucket: 'admasmarket-ef29a.appspot.com',
    measurementId: 'G-5PVZYZXGSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVgVoGpaOpAlR3HLZVYS5GCXSRHTZ-avk',
    appId: '1:331639738061:android:dd2f219c67f5491f78e384',
    messagingSenderId: '331639738061',
    projectId: 'admasmarket-ef29a',
    storageBucket: 'admasmarket-ef29a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8c19LMjA324CHhtUUTIDplRWiOqCFA48',
    appId: '1:331639738061:ios:2d481bfbdd1a55d878e384',
    messagingSenderId: '331639738061',
    projectId: 'admasmarket-ef29a',
    storageBucket: 'admasmarket-ef29a.appspot.com',
    iosBundleId: 'com.amanyize.lunaMarket',
  );
}
